### ISSUE TITLE
Simpler API

### ISSUE THREAD

**Issue by adriendelsalle** [ssg-aero/gbs#1]
Hi! Thank you for this project!

Do you consider your API have to stick with OpenCascade API or maybe think to introduce a simpler one?

`Extrema_PC`, standing for `ExtremaPointCurve` for example, is not very explicit for people who never had to deal with the OCCT API.

Thanks!

**Comment by ssg-aero** [comment]
Hi thank you for your visit and feedback!
 
After struggling several years with OCCT API, I understand the importance of the topic you tackled.

BTW, the functions you quoted are the few ones I kept names.

In the case you mentioned, I made my decision to have a shorter function name and  Camel Case is preferred for methods.

What about proj_point_curve, proj_point_surface, intersect_curve_surface?

Sébastien

**Comment by adriendelsalle** [comment]
Hi!

Naming conventions are often a matter of choice, I have a preference for sticking with what Google published in its [C++ style guide](https://google.github.io/styleguide/cppguide.html#Naming). That is said, it's your choice! :)

**Comment by ssg-aero** [comment]
Thanks, I'll have a look, this king of refactoring is not complex at this time of the project.

I was following some old naming convention.

**Comment by ssg-aero** [comment]
I've made some refactoring work, please have a look on the dedicated branch.

The convention would be Camel Case for Classes methods, Pascal Case for Class and function.

PS:

The previous convention (underscore for functions) was to stick to Boost and stl convention and highlight better functions

**Comment by ssg-aero** [comment]
Refactor done
