### ISSUE TITLE
Discretization for trimmed surface

### ISSUE THREAD

**Issue by tzw28** [ssg-aero/gbs#10]
Looks like current discretization method for NURBS surface only supports surfaces bounded by straight lines. Are there any plans to extend the method to support trimmed surface with any curve bounds?

**Comment by ssg-aero** [comment]
Hello, 
I'm working on a topology module to support face creation.
So yes it is planned.

Regards,

Sebastien

**Comment by tzw28** [comment]
Looking forward to it!
