### ISSUE TITLE
Consider using xtensor?

### ISSUE THREAD

**Issue by adriendelsalle** [ssg-aero/gbs#2]
Hi!

For both simd optimizations and clean numpy style code in C++, maybe you could consider using `xtensor`.

You could that way also leverage its in place use of numpy arrays using `xtensor-python` or bindings to BLAS and LAPACK libraries using `xtensor-blas`.

**Comment by ssg-aero** [comment]
Thanks for the advice, I had a look at xtensor, it's interesting but replace std::vector by xt::xarray would involve a huge refactoring.

I need to make some performances evaluation to make my decision.

**Comment by adriendelsalle** [comment]
Hi! Fair enough 😉. Let me know if you plan such a move.

**Comment by ssg-aero** [comment]
Hi,

I've made some test and for now, on my laptop xtensor optimization is not enabled.
So for now performances tests comparison with std::vector, shows no improvements.

I' afraid this option is too much hardware dependant.

**Comment by adriendelsalle** [comment]
Thanks for the feedback. Did you used xsimd ?

**Comment by ssg-aero** [comment]
Yep
```c++
#include <cstddef>
#include <vector>
#include "xsimd/xsimd.hpp"
#include "xsimd/stl/algorithms.hpp"

const size_t size_v = 1000000;
const size_t n_it = 10000;

TEST(tests_datastorage, xsimd_perfo)
{
    {
        const auto t1 = std::chrono::high_resolution_clock::now();
        using vector_type = std::vector<double, xsimd::aligned_allocator<double, XSIMD_DEFAULT_ALIGNMENT>>;
        vector_type a(size_v);
        vector_type b(size_v);
        vector_type c(size_v);
        for (auto i = 0; i < n_it; i++)
            xsimd::transform(
                // std::execution::par, // not working
                a.begin(), a.end(), b.begin(), c.begin(),
                [](const auto &x, const auto &y) { return (x + y) / 2.; });
        const auto t2 = std::chrono::high_resolution_clock::now();
        const std::chrono::duration<double, std::milli> ms = t2 - t1;
        std::cerr << std::fixed << "xtensor container "
                  << " took " << ms.count() << " ms\n";
    }
    {
        const auto t1 = std::chrono::high_resolution_clock::now();
        std::vector<double> a(size_v);
        std::vector<double> b(size_v);
        std::vector<double> c(size_v);
        for (auto i = 0; i < n_it; i++)
            std::transform(
                a.begin(), a.end(), b.begin(), c.begin(),
                [](const auto &x, const auto &y) { return (x + y) / 2.; });
        const auto t2 = std::chrono::high_resolution_clock::now();
        const std::chrono::duration<double, std::milli> ms = t2 - t1;
        std::cerr << std::fixed << "stl container "
                  << " took " << ms.count() << " ms\n";
    }
    {
        const auto t1 = std::chrono::high_resolution_clock::now();
        std::vector<double> a(size_v);
        std::vector<double> b(size_v);
        std::vector<double> c(size_v);
        for (auto i = 0; i < n_it; i++)
            std::transform(
                std::execution::par,
                a.begin(), a.end(), b.begin(), c.begin(),
                [](const auto &x, const auto &y) { return (x + y) / 2.; });
        const auto t2 = std::chrono::high_resolution_clock::now();
        const std::chrono::duration<double, std::milli> ms = t2 - t1;
        std::cerr << std::fixed << "stl container  execution::par"
                  << " took " << ms.count() << " ms\n";
    }
}
```
Output:
xtensor container  took 9490.064500 ms
stl container  took 9522.697500 ms
stl container  execution::par took 2424.934700 ms

**Comment by ssg-aero** [comment]
For now, the lack of improvement vs std::vector c++17 and the incompatibility with std::execution::par makes difficult to consider refactoring

**Comment by adriendelsalle** [comment]
Hi Sébastien.
Thank you for having considered this option and sharing this benchmark!
I totally understand your point and will try to better understand in the coming months if such a lib can help in this use case.

Maybe keep it in mind if you want later to implement a Python binding with `pybind11` where `stl` containers are passed using copy when `xtensor`/`pytensor` allow to use numpy arrays inplace (zero copy).
See the `pybind11` [documentation](https://pybind11.readthedocs.io/en/stable/advanced/cast/stl.html) and this [article about xtensor](https://medium.com/@SylvainCorlay/scientific-computing-in-a-polyglot-world-with-xtensor-d81ff3865d6).

**Comment by ssg-aero** [comment]
You are welcome, BTW I'm working on an other project in parallel and for this one I' make an interface array class witch will be able to use via templates several containers (std,xtensors, thrus, boost, ...)

Regarding array copying have you had a look at:
[https://pybind11.readthedocs.io/en/stable/advanced/cast/stl.html#making-opaque-types](url)
