### ISSUE TITLE
Add cmake configuration files

### ISSUE THREAD

**Issue by adriendelsalle** [ssg-aero/gbs#3]
Hi!

You could add cmake configuration files to enable the use of this lib through a cmake `find_package` command.

It will be particularly useful when packaged with `conda` or `conan`. I can propose you a PR for this.

**Comment by ssg-aero** [comment]
Well I see what you mean, but for now my cmake's knowledge is not good enough to get what I want.

It will be nice to use modules to get things this way:

GBS::CORE
GBS::RENDER
GBS::OCCT

**Comment by adriendelsalle** [comment]
I'm not mastering CMake neither! CMake needs a lot of practice and is not an example of documentation.

I'll try a PR soon

**Comment by ssg-aero** [comment]
Hi don't know if you had time to work on it, but I've made a proposal.
know lib can be linked after using find_package command using name space.
example:
GBS::render

**Comment by ssg-aero** [comment]
PR merged
