### ISSUE TITLE
Simplify CMakeLists files

### ISSUE THREAD

**Issue by adriendelsalle** [ssg-aero/gbs#4]
The `render` and `occt-utils` CMakeLists files could be more generic and simplified by passing only a `PREFIX` variable to the cmake command.

This would make installation and packaging agnostic of the package manager, especially when using it from sources.

I can propose a PR for that!

**Comment by ssg-aero** [comment]
I don't get what you mean, can you show me an example?

Thanks!

**Comment by adriendelsalle** [comment]
Hi!

I will submit a PR next week, it will be more explicit!

**Comment by ssg-aero** [comment]
Ok thanks.
