### ISSUE TITLE
Missing header to build `yams` (`linux-64` package is not up-to-date)

### ISSUE THREAD

**Issue by adriendelsalle** [ssg-aero/gbs#7]
Description
---

I get an error when building downstream package `yams` on linux-64 due to missing header `gbs-mesh/smoothing.h`

```bash
fatal error: gbs-mesh/smoothing.h: No such file or directory
    6 | #include <gbs-mesh/smoothing.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
```
Looks like on your `conda` channel `ssg-aero` that the linux-64 package is still at `0.1.3` and not latest `0.1.9` (see https://anaconda.org/ssg-aero/gbs).
Is it possible to package it?
Thanks!

**Comment by ssg-aero** [comment]
It will be done asap.

**Comment by ssg-aero** [comment]
A package has been build with WSL, let see if it works.

**Comment by elac-safran** [comment]
> 

Great, thanks!

**Comment by adriendelsalle** [comment]
The build of the cli/executable is fixed thanks!
Now I get error on the Python bindings, but nothing to do with `gbs` I'll open an issue on `yams`.

Thanks!
